up to 6.10.3
patch to fix compilation with glib2 >= 2.78 built againtst glibc >= 2.43.
glibc 2.43 added support for free_sized() which glib2 >= 2.78 makes use
of if detected at build time. however g_free() becomes a macro then
causing build failure in qt:

error: expected id-expression before '(' token